### PR TITLE
change template path to the newer one

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
| Q             | A
| ------------- | ---
| Branch?       | bug fix needs a new release
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? no
| License       | MIT

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
oh ... that means my green test shouldn't make me that happy

**Comment by ElectricMaxxx** [comment]
uh, now i see more :-) i miss `sonata.templating` as a service now.

**Comment by ElectricMaxxx** [comment]
Or just an other issue with SF4

**Comment by dbu** [comment]
thanks!

**Pull request merged**
