### PR TITLE
CmfBlockExtension cleanup

### PR DESCRIPTION
**Pull request by pamil**
Just some random changes to simplify the code and to make it more defensive.

### CODE REVIEW

**Comment by dbu** [comment]
thank you, good cleanups!

**Comment by pamil** [comment]
@dbu is there some roadmap for Symfony CMF 2.0 release? I might help :)

**Comment by dbu** [comment]
there is a discussion in https://github.com/symfony-cmf/symfony-cmf/issues/235 and most notably this spreadsheet https://docs.google.com/spreadsheets/d/1taPM0QrKhRsbsTR9LgLW-cFzKj41x4XbhuxfWKXfz9M/edit?usp=sharing (which might be not completely up to date)

i think we got pretty far with moving the sonata admins to the separate sonata-admin-integration-bundle. what remains is checking for deprecation comments we did and remove that code, and cleanup the code to be php 5.5 (use class constants, avoid unused variables and other general housekeeping)

**Comment by ElectricMaxxx** [comment]
We should also have a look into the documentation. There is some stuff missing and lots of stuff needs to be moved.

**Pull request merged**
